#!/usr/bin/env bash
# Builds dist/<theme>.css bundles (reset + core + theme [+ chrome]) and
# dist/themes.json, the machine-readable index consuming apps and demo.html
# both read so nobody has to hardcode or scrape the theme list.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root"

mkdir -p dist
# Start from an empty dist/: a bundle for a theme that was removed or
# renamed would otherwise stay on disk, stay committed (the dist-sync check
# only sees files a build changes), and keep feeding themes.json's version.
rm -f dist/*.css dist/themes.json

# Bundled CSS sits one directory deeper than the theme sources it's built
# from, so relative url() references (the LCARS @font-face) would 404 from
# dist/. Apps serve assets/ next to dist/, so rewrite to ../assets/.
rewrite_urls() { sed 's#url("assets/#url("../assets/#g; s#url(assets/#url(../assets/#g'; }

# core/ftl-reset.css + ftl-core.css alone, with no theme and no layout
# shell — for an app that wants the --ftl-* token contract and component
# structure but supplies its own palette (color-only adoption), or that
# will never adopt the .ftl-app shell. See CONTRACT.md "Color-only
# adoption". No components are USABLE until a theme (or the app itself)
# defines the tokens they read — this file supplies structure, not look.
{
  echo "/* ftl-themes: core structure only (reset + components), no theme, no"
  echo " * app shell. See CONTRACT.md \"Color-only adoption\" — components need"
  echo " * a theme (or your own --ftl-* values) layered on top before they"
  echo " * have a look at all. Build identity lives in dist/themes.json, not"
  echo " * here, so this file's content stays stable across rebuilds of the"
  echo " * same source and doesn't spuriously fail the dist-sync check. */"
  cat core/ftl-reset.css
  cat core/ftl-core.css
} > dist/ftl-core.css
echo "built dist/ftl-core.css"

for dir in themes/*/; do
  name="$(basename "$dir")"
  src="themes/${name}/theme.css"
  # Same rule as build_bundles.py/build_manifest.py: a directory without a
  # theme.css is not a theme (a half-scaffolded or leftover folder).
  [ -f "$src" ] || continue
  out="dist/${name}.css"
  {
    echo "/* ftl-themes: ${name} — generated by scripts/build.sh."
    echo " * Do not edit; edit themes/${name}/theme.css instead. */"
    cat core/ftl-reset.css
    cat core/ftl-core.css
    cat core/ftl-layout.css
    cat "$src"
    if [ -f "themes/${name}/chrome.css" ]; then cat "themes/${name}/chrome.css"; fi
  } | rewrite_urls > "$out"
  echo "built $out"
done

# Manifest (including per-theme scheme/luminance and build identity) is
# generated in Python — its derivations must match what check.py re-derives,
# and check.py imports them from this script rather than re-implementing.
python3 scripts/build_bundles.py >/dev/null
python3 scripts/build_manifest.py
