#!/usr/bin/env python3
"""Builds dist/icons/<slug>.svg — one merged icon sprite per theme.

Every theme MAY ship themes/<slug>/icons.svg containing only the
<symbol id="icon-name"> entries it wants to override, drawn in that
theme's own visual language. This script starts from a full copy of the
generic sprite (assets/icons/icons.svg) and, for every symbol id a theme
also defines, replaces that symbol with the theme's version (same id, so
every existing <use href="...#icon-name"/> keeps working unchanged).
Themes that ship no icons.svg get dist/icons/<slug>.svg as a straight
copy of the generic sprite — the fallback case has to work with zero
per-theme files, so every theme still gets a merged sprite generated for
it, even when there is nothing to merge.

dist/icons/generic.svg is also written, so an app can link the fallback
sprite directly before any theme is picked (see CONTRACT.md "Icon
system").
"""
import glob
import os
import re

SYMBOL_RE = re.compile(r'<symbol\s+id="([\w-]+)"[^>]*>.*?</symbol>', re.DOTALL)


def parse_symbols(text):
    """{id: full "<symbol ...>...</symbol>" markup} in source order."""
    return {m.group(1): m.group(0) for m in SYMBOL_RE.finditer(text)}


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    os.chdir(root)

    generic_path = "assets/icons/icons.svg"
    generic_text = open(generic_path, encoding="utf-8").read()
    generic_symbols = parse_symbols(generic_text)
    if not generic_symbols:
        raise SystemExit(f"{generic_path}: no <symbol id=\"...\"> entries found")

    os.makedirs("dist/icons", exist_ok=True)
    for path in glob.glob("dist/icons/*.svg"):
        os.remove(path)

    with open("dist/icons/generic.svg", "w", encoding="utf-8") as f:
        f.write(generic_text)
    print("built dist/icons/generic.svg")

    for theme_dir in sorted(glob.glob("themes/*/")):
        slug = os.path.basename(os.path.dirname(theme_dir))
        if not os.path.isfile(os.path.join(theme_dir, "theme.css")):
            continue  # not a theme (see build.sh)

        override_path = os.path.join(theme_dir, "icons.svg")
        merged = dict(generic_symbols)
        overridden = []
        if os.path.isfile(override_path):
            override_symbols = parse_symbols(open(override_path, encoding="utf-8").read())
            unknown = [sid for sid in override_symbols if sid not in generic_symbols]
            if unknown:
                raise SystemExit(
                    f"{override_path}: overrides unknown icon id(s) {unknown} — "
                    f"every override must replace an id that exists in {generic_path}")
            merged.update(override_symbols)
            overridden = sorted(override_symbols)

        body = "\n    ".join(merged[sid] for sid in generic_symbols)  # generic's own order
        out = (
            f'<svg xmlns="http://www.w3.org/2000/svg" style="display:none">\n'
            f'  <!-- ftl-themes: dist/icons/{slug}.svg — generated by scripts/build_icons.py.\n'
            f'       Do not edit; edit assets/icons/icons.svg and/or\n'
            f'       themes/{slug}/icons.svg instead.\n'
            f'       {"Overrides: " + ", ".join(overridden) if overridden else "No per-theme overrides — this is the generic sprite."} -->\n'
            f'  <defs>\n    {body}\n  </defs>\n'
            f'</svg>\n'
        )
        with open(f"dist/icons/{slug}.svg", "w", encoding="utf-8") as f:
            f.write(out)
        print(f"built dist/icons/{slug}.svg" + (f" ({len(overridden)} override(s))" if overridden else ""))


if __name__ == "__main__":
    main()
