#!/usr/bin/env bash
# Builds dist/<theme>.css bundles: ftl-reset.css + ftl-core.css + each
# themes/<name>/theme.css (+ chrome.css if present), concatenated in that
# order. This is the single-file drop-in consuming apps can link directly,
# so they don't need three separate <link> tags per theme.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root"

mkdir -p dist

for dir in themes/*/; do
  name="$(basename "$dir")"
  out="dist/${name}.css"
  {
    echo "/* ftl-themes: ${name} — generated by scripts/build.sh. Do not edit"
    echo " * this file directly; edit themes/${name}/theme.css instead. */"
    cat core/ftl-reset.css
    cat core/ftl-core.css
    cat "themes/${name}/theme.css"
    if [ -f "themes/${name}/chrome.css" ]; then
      cat "themes/${name}/chrome.css"
    fi
  } > "$out"
  echo "built $out"
done
