#!/usr/bin/env python3
"""Builds the two opt-in bundle forms next to each dist/<slug>.css:

dist/<slug>.layered.css — the same bundle inside cascade layers
  (@layer ftl.reset, ftl.core, ftl.layout, ftl.theme). Any unlayered app
  CSS, or a later-declared layer, beats every library rule regardless of
  specificity. Opt-in: switching an existing app to it flips any place the
  app relied on library-wins-by-specificity (CONTRACT.md "Cascade layers").

dist/<slug>-tokens.css — the theme's tokens only: its html[data-theme]
  blocks (palette variants included), @font-face, and element-level rules
  (headings etc.). No .ftl-* component or shell rules. For apps that keep
  their own markup and only want the palette (CONTRACT.md "Adoption levels").
"""
import re
from pathlib import Path

import cssparse

ROOT = Path(__file__).resolve().parent.parent
DIST = ROOT / "dist"


def rewrite_urls(css):
    return css.replace('url("assets/', 'url("../assets/').replace("url(assets/", "url(../assets/")


def statements(css):
    """Top-level statements: (prelude, body) for blocks, (text, None) otherwise."""
    return cssparse.statements(cssparse.strip_comments(css))


def tokens_only(css):
    kept = []
    for prelude, body in statements(css):
        if body is None or not prelude:
            continue
        if prelude.startswith("@font-face") or prelude.startswith("@keyframes"):
            kept.append(f"{prelude} {{{body}}}")
        elif prelude.startswith("@media") or prelude.startswith("@supports"):
            inner = tokens_only(body)
            if inner.strip():
                kept.append(f"{prelude} {{\n{inner}\n}}")
        elif not prelude.startswith("@"):
            # split_top, not split(","): `:is(h1, h2)` is one selector.
            sels = [s for s in cssparse.split_top(prelude) if ".ftl-" not in s]
            if sels:
                kept.append(f"{', '.join(sels)} {{{body}}}")
    return "\n".join(kept)


def main():
    reset = (ROOT / "core/ftl-reset.css").read_text()
    core = (ROOT / "core/ftl-core.css").read_text()
    layout = (ROOT / "core/ftl-layout.css").read_text()
    for d in sorted((ROOT / "themes").iterdir()):
        src = d / "theme.css"
        if not src.exists():
            continue
        slug = d.name
        theme = src.read_text()
        chrome = (d / "chrome.css").read_text() if (d / "chrome.css").exists() else ""
        header = f"/* ftl-themes: {slug} — generated by scripts/build_bundles.py. Do not edit. */\n"

        layered = (
            header + "@layer ftl.reset, ftl.core, ftl.layout, ftl.theme;\n"
            # @font-face can't be meaningfully layered; hoist it out.
            + "".join(f"{p} {{{b}}}\n" for p, b in statements(theme) if p.startswith("@font-face"))
            + f"@layer ftl.reset {{\n{reset}\n}}\n@layer ftl.core {{\n{core}\n}}\n"
            + f"@layer ftl.layout {{\n{layout}\n}}\n@layer ftl.theme {{\n"
            + re.sub(r"@font-face\s*\{[^}]*\}", "", theme) + chrome + "\n}\n"
        )
        (DIST / f"{slug}.layered.css").write_text(rewrite_urls(layered))
        (DIST / f"{slug}-tokens.css").write_text(rewrite_urls(header + tokens_only(theme) + "\n"))
        print(f"built dist/{slug}.layered.css, dist/{slug}-tokens.css")


if __name__ == "__main__":
    main()
