#!/usr/bin/env python3
"""Builds dist/tokens.css next to the per-theme dist/<slug>.css bundles.

dist/tokens.css — every theme's tokens only, concatenated into one file:
  each theme's html[data-theme] blocks (palette variants included),
  @font-face, and element-level rules (headings etc.), with no .ftl-*
  component or shell rules. For apps that keep their own markup and only
  want the palette (CONTRACT.md "Adoption levels") — one link, then switch
  palettes by changing data-theme, no stylesheet swap needed, since every
  theme's rules already live behind its own html[data-theme="slug"] scope
  and can't collide.

Cascade-layer bundles (formerly a second dist/<slug>.layered.css file per
theme) are gone: layering a bundle is one line an app adds itself —
@import url("dist/<slug>.css") layer(ftl); — so pre-building 26 near-
identical wrapped copies bought nothing. See CONTRACT.md "Cascade layers".
"""
from pathlib import Path

import cssparse

ROOT = Path(__file__).resolve().parent.parent
DIST = ROOT / "dist"


def rewrite_urls(css):
    return css.replace('url("assets/', 'url("../assets/').replace("url(assets/", "url(../assets/")


def tokens_only(css):
    kept = []
    for prelude, body in cssparse.statements(cssparse.strip_comments(css)):
        if body is None or not prelude:
            continue
        if prelude.startswith("@font-face") or prelude.startswith("@keyframes"):
            kept.append(f"{prelude} {{{body}}}")
        elif prelude.startswith("@media") or prelude.startswith("@supports"):
            inner = tokens_only(body)
            if inner.strip():
                kept.append(f"{prelude} {{\n{inner}\n}}")
        elif not prelude.startswith("@"):
            # split_top, not split(","): `:is(h1, h2)` is one selector.
            sels = [s for s in cssparse.split_top(prelude) if ".ftl-" not in s]
            if sels:
                kept.append(f"{', '.join(sels)} {{{body}}}")
    return "\n".join(kept)


def main():
    parts = ["/* ftl-themes: every theme's tokens, generated by "
             "scripts/build_bundles.py. Do not edit.\n"
             " * Each theme's rules live under its own html[data-theme=\"slug\"] "
             "scope, so they never collide —\n"
             " * link this once and switch palettes by changing data-theme, no "
             "stylesheet swap needed. */\n"]
    for d in sorted((ROOT / "themes").iterdir()):
        src = d / "theme.css"
        if not src.exists():
            continue
        parts.append(f"\n/* --- {d.name} --- */\n")
        parts.append(tokens_only(src.read_text()))
        parts.append("\n")
    (DIST / "tokens.css").write_text(rewrite_urls("".join(parts)))
    print("built dist/tokens.css")


if __name__ == "__main__":
    main()
